name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clang
      run: sudo apt-get update && sudo apt-get install -y clang tree

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=/usr/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/
      run: |
        echo ${PWD}
        tree -L 2
        ./build/Debug/myProg ./fileToCopy.txt out.txt
        FC fileToCopy.txt build/out.txt > build/comparing_log.txt 2>&1
        if [ "$$?" -eq 0 ]; then
          echo "Files are equal"
        else
          echo "Files are different"
        fi
